-- One row per generated jingle, kept even when the jingle is deleted,
-- so the monthly generation limit can't be reset by deleting jingles.
CREATE TABLE jingle_generations
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    created_by      VARCHAR(255)                            NOT NULL,
    organization_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_jingle_generations PRIMARY KEY (id),
    CONSTRAINT fk_jingle_generations_on_organization FOREIGN KEY (organization_id) REFERENCES organizations (id) ON DELETE CASCADE
);

CREATE INDEX idx_jingle_generations_org_created ON jingle_generations (organization_id, created_at);

INSERT INTO jingle_generations (created_at, created_by, organization_id)
SELECT created_at, created_by, organization_id
FROM jingles
WHERE organization_id IS NOT NULL;
