-- AI music generation: one row per track we ask a provider to make.
-- A job waits in the queue, is generated and checked, then waits for a person
-- to approve it; only approved tracks are copied into musics and reach stores.
CREATE TABLE music_generation_jobs
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    requested_by           VARCHAR(255)                            NOT NULL,
    atmosphere             VARCHAR(255)                            NOT NULL,
    mood                   VARCHAR[]                               NOT NULL,
    variation              INTEGER                                 NOT NULL,
    prompt                 TEXT                                    NOT NULL,
    length_seconds         INTEGER                                 NOT NULL,
    provider               VARCHAR(64)                             NOT NULL,
    status                 VARCHAR(32)                             NOT NULL,
    attempts               INTEGER                                 NOT NULL DEFAULT 0,
    cost_usd               NUMERIC(10, 4)                          NOT NULL DEFAULT 0,
    last_error             TEXT,
    file_url               VARCHAR(512),
    duration_seconds       DOUBLE PRECISION,
    loudness_lufs          DOUBLE PRECISION,
    longest_silence_seconds DOUBLE PRECISION,
    quality_notes          TEXT,
    music_id               BIGINT,
    started_at             TIMESTAMP WITHOUT TIME ZONE,
    finished_at            TIMESTAMP WITHOUT TIME ZONE,
    reviewed_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_music_generation_jobs PRIMARY KEY (id)
);

CREATE INDEX idx_music_generation_jobs_status ON music_generation_jobs (status, id);
CREATE INDEX idx_music_generation_jobs_started ON music_generation_jobs (started_at);
