-- Requests left through the form on the public landing page.
CREATE TABLE landing_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    company_name VARCHAR(160)                            NOT NULL,
    email        VARCHAR(254)                            NOT NULL,
    language     VARCHAR(8)                              NOT NULL,
    CONSTRAINT pk_landing_requests PRIMARY KEY (id)
);
